package ISC::BIND::Stats::Sample;

use strict;
use Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);

$VERSION     = 1.00;
@ISA         = qw(Exporter);
@EXPORT      = qw($sample1);
@EXPORT_OK   = qw($sample1);

our $sample1 = {
          'server_counters' => {
                                 'requests' => {
                                                 'zonestat' => {
                                                                 'AXFRReqv6' => '0',
                                                                 'SOAOutv6' => '0',
                                                                 'NotifyOutv6' => '0',
                                                                 'NotifyRej' => '42',
                                                                 'AXFRReqv4' => '0',
                                                                 'XfrSuccess' => '3',
                                                                 'NotifyOutv4' => '648',
                                                                 'SOAOutv4' => '5885',
                                                                 'IXFRReqv6' => '0',
                                                                 'NotifyInv4' => '300',
                                                                 'XfrFail' => '786',
                                                                 'IXFRReqv4' => '789',
                                                                 'NotifyInv6' => '0'
                                                               },
                                                 'nsstat' => {
                                                               'ReqSIG0' => '0',
                                                               'QryRecursion' => '0',
                                                               'XfrRej' => '0',
                                                               'QryDuplicate' => '0',
                                                               'UpdateRej' => '7037',
                                                               'QryFORMERR' => '0',
                                                               'QrySERVFAIL' => '0',
                                                               'ReqTCP' => '117982',
                                                               'QryNxrrset' => '359881',
                                                               'Requestv4' => '5354426',
                                                               'Requestv6' => '80681',
                                                               'UpdateReqFwd' => '0',
                                                               'Response' => '5434959',
                                                               'UpdateRespFwd' => '0',
                                                               'QryDropped' => '0',
                                                               'RespTSIG' => '2582',
                                                               'UpdateBadPrereq' => '0',
                                                               'RecQryRej' => '0',
                                                               'QrySuccess' => '245822',
                                                               'UpdateFail' => '0',
                                                               'QryReferral' => '3213261',
                                                               'UpdateDone' => '0',
                                                               'ReqBadSIG' => '553',
                                                               'QryAuthAns' => '2213436',
                                                               'UpdateFwdFail' => '0',
                                                               'QryFailure' => '48',
                                                               'ReqTSIG' => '3434',
                                                               'XfrReqDone' => '137',
                                                               'RespSIG0' => '0',
                                                               'AuthQryRej' => '1',
                                                               'ReqBadEDNSVer' => '0',
                                                               'QryNoauthAns' => '3213261',
                                                               'TruncatedResp' => '12472',
                                                               'QryNXDOMAIN' => '1607733',
                                                               'RespEDNS0' => '2913625',
                                                               'ReqEdns0' => '2913625'
                                                             },
                                                 'opcode' => {
                                                               'QUERY' => '5427474',
                                                               'NOTIFY' => '357',
                                                               'UPDATE' => '7041'
                                                             },
                                                 'rdtype' => {
                                                               'AFSDB' => '40',
                                                               'TXT' => '457145',
                                                               'NS' => '123809',
                                                               'SRV' => '52528',
                                                               'AAAA' => '808368',
                                                               'X25' => '1',
                                                               'ANY' => '180328',
                                                               'DLV' => '6',
                                                               'A' => '3399498',
                                                               'IXFR' => '137',
                                                               'CNAME' => '7183',
                                                               'NAPTR' => '20',
                                                               'A6' => '24300',
                                                               'SOA' => '86086',
                                                               'DS' => '5901',
                                                               'MX' => '99362',
                                                               'PTR' => '178687',
                                                               'RRSIG' => '2',
                                                               'DNSKEY' => '236',
                                                               'RESERVED0' => '10',
                                                               'MAILB' => '47',
                                                               'SPF' => '3188'
                                                             }
                                               }
                               },
          'boot_time' => '2012-07-13T12:35:59Z',
          'zone' => {
                      'arpa' => {
                                'serial' => 2012071301,
                                'counters' => {
                                                'updatereqfwd' => '0',
                                                'respedns0' => '0',
                                                'xfrreqdone' => '0',
                                                'requestv6' => '0',
                                                'qrynxdomain' => '16',
                                                'authqryrej' => '0',
                                                'truncatedresp' => '0',
                                                'qrynoauthans' => '29418',
                                                'qrysuccess' => '189',
                                                'qryauthans' => '205',
                                                'qryreferral' => '29418',
                                                'updatebadprereq' => '0',
                                                'reqbadsig' => '0',
                                                'qryduplicate' => '0',
                                                'reqsig0' => '0',
                                                'updaterej' => '0',
                                                'respsig0' => '0',
                                                'updatefwdfail' => '0',
                                                'updatedone' => '0',
                                                'reqbadednsver' => '0',
                                                'qryservfail' => '0',
                                                'qrydropped' => '0',
                                                'qryfailure' => '0',
                                                'xfrrej' => '0',
                                                'qryformerr' => '0',
                                                'updaterespfwd' => '0',
                                                'updatefail' => '0',
                                                'reqedns0' => '0',
                                                'recqryrej' => '0',
                                                'response' => '0',
                                                'reqtsig' => '0',
                                                'qryrecursion' => '0',
                                                'requestv4' => '0',
                                                'qrynxrrset' => '0',
                                                'resptsig' => '0',
                                                'reqtcp' => '0'
                                              }
                              },
                      '.' => {
                             'serial' => 2012071400,
                             'counters' => {
                                             'updatereqfwd' => '0',
                                             'respedns0' => '0',
                                             'xfrreqdone' => '40',
                                             'requestv6' => '0',
                                             'qrynxdomain' => '303733',
                                             'authqryrej' => '0',
                                             'truncatedresp' => '0',
                                             'qrynoauthans' => '740948',
                                             'qrysuccess' => '52451',
                                             'qryauthans' => '456939',
                                             'qryreferral' => '740948',
                                             'updatebadprereq' => '0',
                                             'reqbadsig' => '0',
                                             'qryduplicate' => '0',
                                             'reqsig0' => '0',
                                             'updaterej' => '1673',
                                             'respsig0' => '0',
                                             'updatefwdfail' => '0',
                                             'updatedone' => '0',
                                             'reqbadednsver' => '0',
                                             'qryservfail' => '0',
                                             'qrydropped' => '0',
                                             'qryfailure' => '0',
                                             'xfrrej' => '0',
                                             'qryformerr' => '0',
                                             'updaterespfwd' => '0',
                                             'updatefail' => '0',
                                             'reqedns0' => '0',
                                             'recqryrej' => '0',
                                             'response' => '0',
                                             'reqtsig' => '0',
                                             'qryrecursion' => '0',
                                             'requestv4' => '0',
                                             'qrynxrrset' => '100755',
                                             'resptsig' => '0',
                                             'reqtcp' => '0'
                                           }
                           },
                      'root-servers.net' => {
                                            'serial' => 2011060800,
                                            'counters' => {
                                                            'updatereqfwd' => '0',
                                                            'respedns0' => '0',
                                                            'xfrreqdone' => '0',
                                                            'requestv6' => '0',
                                                            'qrynxdomain' => '3',
                                                            'authqryrej' => '0',
                                                            'truncatedresp' => '0',
                                                            'qrynoauthans' => '0',
                                                            'qrysuccess' => '6086',
                                                            'qryauthans' => '6453',
                                                            'qryreferral' => '0',
                                                            'updatebadprereq' => '0',
                                                            'reqbadsig' => '0',
                                                            'qryduplicate' => '0',
                                                            'reqsig0' => '0',
                                                            'updaterej' => '0',
                                                            'respsig0' => '0',
                                                            'updatefwdfail' => '0',
                                                            'updatedone' => '0',
                                                            'reqbadednsver' => '0',
                                                            'qryservfail' => '0',
                                                            'qrydropped' => '0',
                                                            'qryfailure' => '0',
                                                            'xfrrej' => '0',
                                                            'qryformerr' => '0',
                                                            'updaterespfwd' => '0',
                                                            'updatefail' => '0',
                                                            'reqedns0' => '0',
                                                            'recqryrej' => '0',
                                                            'response' => '0',
                                                            'reqtsig' => '0',
                                                            'qryrecursion' => '0',
                                                            'requestv4' => '0',
                                                            'qrynxrrset' => '364',
                                                            'resptsig' => '0',
                                                            'reqtcp' => '0'
                                                          }
                                          }
                    },
          'sample_time' => '2012-07-14T09:20:00Z'
        };

1;
