---
abstract: ~
author:
  - 'Internet Systems Consortium Inc.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ISC::BIND::Stats
name: ISC-BIND-Stats
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  Getopt::Long: 0
  HTTP::Date: 0
  IO::File: 0
  IO::Uncompress::Bunzip2: 0
  MongoDB: 0
  Time::HiRes: 1.9719
  XML::SAX::Base: 0
  XML::SAX::ParserFactory: 0
  common::sense: 3.3
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.052000
